global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'sarfarazalam1825@gmail.com'
  smtp_auth_username: 'sarfarazalam1825@gmail.com'
  smtp_auth_password: 'ccscixhkbfdtqzcy'

route:
  receiver: email-alerts

receivers:
  - name: email-alerts
    email_configs:
      - to: 'sarfarazalamcool78692@gmail.com'
        send_resolved: true
